version: '3.4'

services:
  extralifebotv2:
    image: extralifebotv2
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 extra_life/bot.py "]
    ports:
      - 5678:5678
