jobs:

  - name: hello_job
    plugin: hello
    schedule: "*/1 * * * *"
    enabled: true

    config:
      message: "Polaris is alive"

  - name: weather_home
    plugin: weather_forecast
    schedule: "0 6 * * *"

    config:
      latitude: 35.4
      longitude: -97.5

      periods: 6
      normal_poll: "*/15 * * * *"
      alert_poll: "*/1 * * * *"
      label: Home     