jobs:

  - name: hello_job
    plugin: hello
    schedule: "*/1 * * * *"
    enabled: true

    config:
      message: "Polaris is alive"

  - name: weather_home
    plugin: weather_forecast
    schedule: "0 6 * * *"

    config:
      latitude: 35.4
      longitude: -97.5

      periods: 6
      normal_poll: "*/15 * * * *"
      alert_poll: "*/1 * * * *"
      label: Home     

  - name: daily_quote
    plugin: quote
    schedule: "0 7 * * *"
    enabled: true
    config: {}

  - name: internet_monitor
    plugin: internet_monitor
    schedule: "0 * * * *"
    enabled: true

    config:
      normal_poll: "0 * * * *"
      degraded_poll: "*/10 * * * *"
      offline_poll: "*/1 * * * *"
      history_size: 10
      degradation_threshold: 0.80    